[profile.default]
optimizer = true
evm_version = "london"
solc_version = "0.8.13" # For your tests
[profile.legacy]
solc_version = "0.5.16" # For Uniswap contracts
remappings = [
    "@uniswap/v2-core/=node_modules/@uniswap/v2-core/",
    "@uniswap/v2-periphery/=node_modules/@uniswap/v2-periphery/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
